### ISSUE TITLE
How do you go about testing this thang?

### ISSUE THREAD

**Issue by rluedde** [ChrisKeefe/jiggety#12]
Do you just run each of the files that aren't "jiggety" in isolation?

At some point I'll probably fork and work on my own version of this bad boy. Seems like a great thing to have. 

What does jiggety mean? 

Is this the right place to be asking questions?

**Comment by rluedde** [comment]
Virtual machine?

**Comment by ChrisKeefe** [comment]
Not sure why I didn't get notifications about this issue, @rluedde. Sorry for the radio silence, and thanks for the meatspace heads-up. 

I generally clone and run this first-thing when setting up a new machine. If you're working with a machine that has data you care about on it already, exercise caution. 

Depending on how cavalier you're feeling, you can `bash jiggety`, answer the questions, and see what blows up, or follow your more-prudent suggestion and run files independently. Maybe better, though, fork jiggety and clone your fork, then read through `jiggety` and the scripts it calls, running  the config commands that you want manually, or editing the scripts to remove the things you're not interested in and running file-by-file or all together. This will give you a pretty good picture of what's happening here, and you'll wind up with a fork that does what _you_ need it to do for next time. 

Jiggety is a reference to the nursery rhyme [To Market, To Market](https://en.wikipedia.org/wiki/To_market,_to_market), found in the line "home again, home again, jiggety jig". I like the sound of jiggety-jigging home, and these scripts have both helped me feel at home with my OS, and made 'coming home' much faster and easier on a new machine. 

What about virtual machines?

**Comment by rluedde** [comment]
Not a worry, good sir. I understand how it goes.

That all makes sense! 

I'm a fan of the rhyme reference, I'll have to come up with a cool name with meaning as well.

I was just thinking that you could be working on this guy on a VM because you're likely going to blow stuff up and blowing stuff up on a VM seems far preferable to blowing it up on your actual machine.

**Comment by ChrisKeefe** [comment]
> I was just thinking that you could be working on this guy on a VM because you're likely going to blow stuff up and blowing stuff up on a VM seems far preferable to blowing it up on your actual machine.

That's probably true, but with LM as my daily driver for a couple years, it has just made more sense to make changes on my actual machine. It's only bitten me once, and that was the product of disregarding rather a lot of warning signs. Generally, I add new features to jiggety by running individual configuration commands directly from a terminal. When they work as expected, they get copy-pasted in. 

If I'm in a place where the contents or behavior of my system are critical to, e.g., meeting a work deadline, I'll sketch the changes in jiggety instead and troubleshoot after a fresh install or once the deadline has been met. Most of these changes, though, are very superficial, affecting only terminal or DE settings, global software installation, backgrounds, whatever. If they break, the worst thing that happens is I have to create a new conda env, factory reset/reinstall my DE or put up with a weird sound/color/whatever for a week or two.

**Comment by rluedde** [comment]
Interesting, thanks!

**Comment by ChrisKeefe** [comment]
Closing this, @rluedde , but feel free to open another issue if you have other questions, or shoot me an email if that's easier.
